### PR TITLE
 Add control change data in `midiToSequenceProto`

### PR DESCRIPTION
**Pull request by e7mac**
Currently, control change data is skipped while parsing MIDI data to proto. This PR adds the ability to read and wrote control change data when parsing to and from MIDI

I also added a corresponding unit test (and correspondingly I updated the MIDI file to include those control changes)

### CODE REVIEW

**Comment by e7mac** [comment]
`yarn test-and-build` works fine locally! Not sure what's different on CI, would love some help!

**Comment by notwaldorf** [comment]
@iansimon do you want to take a look? I think you did the original implementation.....I think

**Comment by notwaldorf** [comment]
@e7mac Looking at the errors in the build, they are:
```
ERROR: (max-line-length) /home/travis/build/magenta/magenta-js/music/src/core/midi_io.ts[108, 1]: Exceeds maximum line length of 80
ERROR: (object-literal-shorthand) /home/travis/build/magenta/magenta-js/music/src/core/midi_io.ts[115, 9]: Expected property shorthand in object literal ('{time}').
ERROR: (object-literal-shorthand) /home/travis/build/magenta/magenta-js/music/src/core/midi_io.ts[116, 9]: Expected property shorthand in object literal ('{controlNumber}').
ERROR: (object-literal-shorthand) /home/travis/build/magenta/magenta-js/music/src/core/midi_io.ts[117, 9]: Expected property shorthand in object literal ('{controlValue}').
```

**Comment by e7mac** [comment]
@notwaldorf I see the errors now, and should be unblocked! Thanks for that!

**Review by iansimon — APPROVED** [review]

**Review by notwaldorf — APPROVED** [review]

**Pull request merged**
